qcheck random seed: 1234
Testing `my test'.
  [OK]          suite          0   list_rev_is_involutive.
  [FAIL]        suite          1   fail_sort_id.
  [FAIL]        suite          2   error_raise_exn.
  [FAIL]        suite          3   fail_check_err_message.
  [OK]          suite          4   tree_rev_is_involutive.
┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        suite          1   fail_sort_id.                               │
└──────────────────────────────────────────────────────────────────────────────┘
test `fail_sort_id` failed on ≥ 1 cases: [1; 0] (after 20 shrink steps)
[exception] test `fail_sort_id` failed on ≥ 1 cases: [1; 0] (after 20 shrink steps)
 ──────────────────────────────────────────────────────────────────────────────
┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        suite          2   error_raise_exn.                            │
└──────────────────────────────────────────────────────────────────────────────┘
test `error_raise_exn`
raised exception `Error`
on `0 (after 63 shrink steps)`
[exception] test `error_raise_exn`
raised exception `Error`
on `0 (after 63 shrink steps)`
 ──────────────────────────────────────────────────────────────────────────────
┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        suite          3   fail_check_err_message.                     │
└──────────────────────────────────────────────────────────────────────────────┘
test `fail_check_err_message` failed on ≥ 1 cases:
0 (after 7 shrink steps)
this
will
always
fail
[exception] test `fail_check_err_message` failed on ≥ 1 cases:
0 (after 7 shrink steps)
this
will
always
fail
 ──────────────────────────────────────────────────────────────────────────────
3 failures! 5 tests run.
